AllCops:
  Exclude:
    - 'permissions.gemspec'
    - 'Guardfile'
    - 'bin/**/*'
    - 'spec/support/skeleton'
  TargetRubyVersion: 2.4

Metrics/BlockLength:
  Exclude:
    - 'spec_helper.rb'
    - 'spec/**/*_spec.rb'

Metrics/LineLength:
  Exclude:
    - 'Guardfile'
    - 'spec_helper.rb'
  Max: 100

Style/Documentation:
  Enabled: false
  Exclude:
    - 'spec/**/*'
    - 'lib/permissions.rb'
